version: "3.8"

services:
  telegram-bot:
    build:
      context: .   # Build from root folder where Dockerfile is
    container_name: telegram-bot
    working_dir: /app
    volumes:
      - ./:/app   # Mount root folder as /app
    command: python bot.py
    env_file:
      - .env
    restart: always

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  n8n_data:
