services:
  telegram-bot:
    image: python:3.11
    container_name: telegram-bot
    working_dir: /app
    volumes:
      - ./samueluyyt-tg-toolkit:/app
      - ./samueluy-docker-n8n-bot/.env:/app/.env
    command: python bot.py
    env_file:
      - .env

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    restart: always
